#!/bin/bash

#SBATCH -p q_student
#SBATCH -N 1
#SBTACH --time=1:00

rm -r lock4

for num_lock in 4
do
for num_threads in 1 2 3 4 5 8 15 16 32 64
	do
	echo $num_threads
	export OMP_NUM_THREADS=$num_threads
	mkdir lock$num_lock
	./fair  $num_threads $num_lock > ./lock$num_lock/out_$num_threads-$num_lock.txt
	wait
	./tp $num_threads $num_lock > ./lock$num_lock/TP_$num_threads-$num_lock.txt
	wait
	./lat $num_threads $num_lock > ./lock$num_lock/LAT_$num_threads-$num_lock.txt
	wait
done
done
